In [1]:
import numpy as np
import pandas as pd
import random

In [ ]:
# structure gets change by use of brackets and the combination
- list []
- tuple ()
- set {}
- 

In [8]:
rollno = list(range(1, 21))
print(type(rollno), rollno)

<class 'list'> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [10]:
sname = ( "Alice", "Bob", "Charlee", "Diana", "Eithan", "Fiona", "George", "Hannah", "Ian", "Jasmin", "kevin", "Lily", "Mike", "Nina", "Oscar", "Priya", "Quinn", "Raj", "Sophia", "Tom")
print(type(sname), list(sname))

<class 'tuple'> ['Alice', 'Bob', 'Charlee', 'Diana', 'Eithan', 'Fiona', 'George', 'Hannah', 'Ian', 'Jasmin', 'kevin', 'Lily', 'Mike', 'Nina', 'Oscar', 'Priya', 'Quinn', 'Raj', 'Sophia', 'Tom']


In [29]:
genders_set = {"Male", "Female", "Male", "Female"}
gender = [random.choice(list(genders_set)) for _ in rollno]
print(list(gender))

['Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female', 'Female']


In [18]:
gender.count('Male')

12

In [30]:
print('Males -', gender.count('Male'), 'Females -', gender.count('Female'))

Males - 7 Females - 13


In [35]:
courses_dict = {1:"CS", 2: "IT", 3: "AI", 4: "DS"}
course = [courses_dict[random.randint(1, 4)] for _ in rollno]
print(list(course))

['DS', 'CS', 'IT', 'DS', 'IT', 'IT', 'IT', 'CS', 'IT', 'IT', 'AI', 'CS', 'CS', 'DS', 'DS', 'DS', 'IT', 'DS', 'DS', 'CS']


In [12]:
np.random.normal(70, 10, len(rollno))

array([81.32174298, 73.56709112, 68.80015902, 70.1090599 , 72.38135156,
       71.42108251, 57.76527292, 71.04980961, 72.50064474, 75.90414184,
       73.21051495, 76.46192853, 71.04627411, 84.83228866, 53.90835552,
       81.32633036, 60.77268601, 60.71544151, 71.57755808, 71.81319109])

In [13]:
score = np.clip(np.random.normal(70, 10, len(rollno)), 40, 100,). round(1)
score

array([64.9, 85.5, 71.6, 58.4, 71.1, 73. , 73.7, 81. , 68.6, 63.4, 60.4,
       70.7, 53.7, 69.4, 67. , 81.8, 52.7, 60.4, 51.1, 61.8])

In [14]:
age = np.random.randint(18, 25, size=len(rollno))
age

array([23, 19, 19, 22, 20, 21, 24, 20, 23, 18, 22, 21, 23, 18, 23, 22, 21,
       24, 20, 23])

In [16]:
np.random.normal(70, 10, len(rollno))

array([67.82537996, 75.93400871, 83.88445659, 69.60934226, 76.9403177 ,
       74.39832716, 58.85992414, 82.91252686, 74.14163701, 89.67687703,
       82.75412459, 67.40126871, 60.11486422, 45.10285138, 56.30496617,
       73.9661642 , 74.44800409, 81.01722483, 87.66413587, 66.36795711])

In [27]:
score = np.random.normal(70, 15, len(rollno))
print(score, ':::', np.mean(score), np.std(score))
score = np.clip(score, 50, 95)
print(score)
score = score.round(1)
print(score)

[54.18549691 48.42003192 76.95237228 87.03879232 76.31369747 80.35152232
 62.99632834 72.91893436 76.2514186  68.69196061 60.75125635 55.99638313
 53.06692341 56.67155915 92.34277484 75.25180503 82.44300207 45.05353783
 82.06542093 61.14007261] ::: 68.44516452354983 13.276866630898422
[54.18549691 50.         76.95237228 87.03879232 76.31369747 80.35152232
 62.99632834 72.91893436 76.2514186  68.69196061 60.75125635 55.99638313
 53.06692341 56.67155915 92.34277484 75.25180503 82.44300207 50.
 82.06542093 61.14007261]
[54.2 50.  77.  87.  76.3 80.4 63.  72.9 76.3 68.7 60.8 56.  53.1 56.7
 92.3 75.3 82.4 50.  82.1 61.1]


In [23]:
a = np.arange(10)
print(a)
np.clip(a, 2,6)

[0 1 2 3 4 5 6 7 8 9]


array([2, 2, 2, 3, 4, 5, 6, 6, 6, 6])

In [32]:
print(rollno, '\n', sname, '\n', gender, '\n', course, '\n', score, '\n', age)

NameError: name 'sname' is not defined

# Step - 2: Data Fram
- rows and columns
- Columns - variable names, Rows-data for each studen
- join Columns to Data Frame
- 20 students data

In [33]:
df = pd.DataFrame({   "rollno": rollno,  "sname": sname, "gender": gender, "course": course, "score": score, "age": age})
df

NameError: name 'sname' is not defined