In [1]:
import numpy as np
import pandas as pd
import random

In [ ]:
# structure gets change by use of brackets and the combination
- list []
- tuple ()
- set {}
- 

In [8]:
rollno = list(range(1, 21))
print(type(rollno), rollno)

<class 'list'> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [10]:
sname = ( "Alice", "Bob", "Charlee", "Diana", "Eithan", "Fiona", "George", "Hannah", "Ian", "Jasmin", "kevin", "Lily", "Mike", "Nina", "Oscar", "Priya", "Quinn", "Raj", "Sophia", "Tom")
print(type(sname), list(sname))

<class 'tuple'> ['Alice', 'Bob', 'Charlee', 'Diana', 'Eithan', 'Fiona', 'George', 'Hannah', 'Ian', 'Jasmin', 'kevin', 'Lily', 'Mike', 'Nina', 'Oscar', 'Priya', 'Quinn', 'Raj', 'Sophia', 'Tom']


In [29]:
genders_set = {"Male", "Female", "Male", "Female"}
gender = [random.choice(list(genders_set)) for _ in rollno]
print(list(gender))

['Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female', 'Female']


In [18]:
gender.count('Male')

12

In [30]:
print('Males -', gender.count('Male'), 'Females -', gender.count('Female'))

Males - 7 Females - 13


In [35]:
courses_dict = {1:"CS", 2: "IT", 3: "AI", 4: "DS"}
course = [courses_dict[random.randint(1, 4)] for _ in rollno]
print(list(course))

['DS', 'CS', 'IT', 'DS', 'IT', 'IT', 'IT', 'CS', 'IT', 'IT', 'AI', 'CS', 'CS', 'DS', 'DS', 'DS', 'IT', 'DS', 'DS', 'CS']


In [38]:
np.random.normal(70, 10, len(rollno))

array([93.07122852, 80.52208131, 60.28606114, 79.72405153, 62.87863058,
       65.42511051, 76.10013066, 68.16472099, 86.8740641 , 74.78520508,
       65.555938  , 58.91217254, 86.54550377, 72.7554585 , 77.68241013,
       65.88977073, 75.53164609, 82.49649007, 60.69957782, 52.01874185])

In [37]:
score = np.clip(np.random.normal(70, 10, len(rollno)), 40, 100,). round(1)
score

array([92.4, 75.8, 66.1, 80.4, 74. , 76.8, 74.9, 54.3, 68.6, 82.2, 50. ,
       77.5, 54.1, 64.5, 67.6, 71.7, 84.8, 72.7, 90.8, 70. ])

In [40]:
age = np.random.randint(18, 25, size=len(rollno))
age

array([21, 22, 24, 19, 18, 20, 24, 21, 19, 22, 24, 19, 21, 18, 23, 22, 20,
       23, 23, 20])